//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClientApp.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Système de traitement astronomique.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculer la distance.
        /// </summary>
        internal static string BtnCalculateDistance {
            get {
                return ResourceManager.GetString("BtnCalculateDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculer l’horizon.
        /// </summary>
        internal static string BtnCalculateHorizon {
            get {
                return ResourceManager.GetString("BtnCalculateHorizon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculer la vitesse.
        /// </summary>
        internal static string BtnCalculateVelocity {
            get {
                return ResourceManager.GetString("BtnCalculateVelocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convertir la température.
        /// </summary>
        internal static string BtnConvertTemperature {
            get {
                return ResourceManager.GetString("BtnConvertTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizon des événements.
        /// </summary>
        internal static string LblEventHorizon {
            get {
                return ResourceManager.GetString("LblEventHorizon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResultRésultat.
        /// </summary>
        internal static string LblResult {
            get {
                return ResourceManager.GetString("LblResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance de l’étoile.
        /// </summary>
        internal static string LblStarDistance {
            get {
                return ResourceManager.GetString("LblStarDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vitesse de l’étoile.
        /// </summary>
        internal static string LblStarVelocity {
            get {
                return ResourceManager.GetString("LblStarVelocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Température (Kelvin).
        /// </summary>
        internal static string LblTemperatureKelvin {
            get {
                return ResourceManager.GetString("LblTemperatureKelvin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couleur d’arrière-plan.
        /// </summary>
        internal static string MenuBackgroundColor {
            get {
                return ResourceManager.GetString("MenuBackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anglais.
        /// </summary>
        internal static string MenuEnglish {
            get {
                return ResourceManager.GetString("MenuEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Police.
        /// </summary>
        internal static string MenuFont {
            get {
                return ResourceManager.GetString("MenuFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Français.
        /// </summary>
        internal static string MenuFrench {
            get {
                return ResourceManager.GetString("MenuFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allemand.
        /// </summary>
        internal static string MenuGerman {
            get {
                return ResourceManager.GetString("MenuGerman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Langue.
        /// </summary>
        internal static string MenuLanguage {
            get {
                return ResourceManager.GetString("MenuLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode nuit.
        /// </summary>
        internal static string MenuNightMode {
            get {
                return ResourceManager.GetString("MenuNightMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thème.
        /// </summary>
        internal static string MenuTheme {
            get {
                return ResourceManager.GetString("MenuTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrée invalide.
        /// </summary>
        internal static string MsgInvalidInput {
            get {
                return ResourceManager.GetString("MsgInvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valeur hors limites.
        /// </summary>
        internal static string MsgOutOfRange {
            get {
                return ResourceManager.GetString("MsgOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server errorErreur du serveur.
        /// </summary>
        internal static string MsgServerError {
            get {
                return ResourceManager.GetString("MsgServerError", resourceCulture);
            }
        }
    }
}
