//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClientApp.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Astronomical Processing System\nClient Application\nSupports language switching and UI customisation..
        /// </summary>
        internal static string AboutMessage {
            get {
                return ResourceManager.GetString("AboutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Info.
        /// </summary>
        internal static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Astronomical Processing System.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate Distance.
        /// </summary>
        internal static string BtnCalculateDistance {
            get {
                return ResourceManager.GetString("BtnCalculateDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate Horizon.
        /// </summary>
        internal static string BtnCalculateHorizon {
            get {
                return ResourceManager.GetString("BtnCalculateHorizon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate Velocity.
        /// </summary>
        internal static string BtnCalculateVelocity {
            get {
                return ResourceManager.GetString("BtnCalculateVelocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert Temperature.
        /// </summary>
        internal static string BtnConvertTemperature {
            get {
                return ResourceManager.GetString("BtnConvertTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star Distance (Parallax).
        /// </summary>
        internal static string GrpDistance {
            get {
                return ResourceManager.GetString("GrpDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black Hole Event Horizon (Schwarzschild Radius).
        /// </summary>
        internal static string GrpRadius {
            get {
                return ResourceManager.GetString("GrpRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature Conversion (°C to K).
        /// </summary>
        internal static string GrpTemperature {
            get {
                return ResourceManager.GetString("GrpTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star Velocity (Doppler Effect).
        /// </summary>
        internal static string GrpVelocity {
            get {
                return ResourceManager.GetString("GrpVelocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature (°C):.
        /// </summary>
        internal static string LblCelsiusFull {
            get {
                return ResourceManager.GetString("LblCelsiusFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Horizon.
        /// </summary>
        internal static string LblEventHorizon {
            get {
                return ResourceManager.GetString("LblEventHorizon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature (K):.
        /// </summary>
        internal static string LblKelvin {
            get {
                return ResourceManager.GetString("LblKelvin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance (km):.
        /// </summary>
        internal static string LblKm {
            get {
                return ResourceManager.GetString("LblKm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance (light-years):.
        /// </summary>
        internal static string LblLightYears {
            get {
                return ResourceManager.GetString("LblLightYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black Hole Mass (kg):.
        /// </summary>
        internal static string LblMass {
            get {
                return ResourceManager.GetString("LblMass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observed Wavelength (nm):.
        /// </summary>
        internal static string LblObserved {
            get {
                return ResourceManager.GetString("LblObserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parallax Angle (arcsec):.
        /// </summary>
        internal static string LblParallax {
            get {
                return ResourceManager.GetString("LblParallax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance (parsecs):.
        /// </summary>
        internal static string LblParsecs {
            get {
                return ResourceManager.GetString("LblParsecs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schwarzschild Radius (m):.
        /// </summary>
        internal static string LblRadius {
            get {
                return ResourceManager.GetString("LblRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rest Wavelength (nm):.
        /// </summary>
        internal static string LblRest {
            get {
                return ResourceManager.GetString("LblRest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        internal static string LblResult {
            get {
                return ResourceManager.GetString("LblResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star Distance.
        /// </summary>
        internal static string LblStarDistance {
            get {
                return ResourceManager.GetString("LblStarDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star Velocity.
        /// </summary>
        internal static string LblStarVelocity {
            get {
                return ResourceManager.GetString("LblStarVelocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature (Kelvin).
        /// </summary>
        internal static string LblTemperatureKelvin {
            get {
                return ResourceManager.GetString("LblTemperatureKelvin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radial Velocity (m/s):.
        /// </summary>
        internal static string LblVelocity {
            get {
                return ResourceManager.GetString("LblVelocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Info.
        /// </summary>
        internal static string MenuAboutApp {
            get {
                return ResourceManager.GetString("MenuAboutApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Colour.
        /// </summary>
        internal static string MenuBackgroundColor {
            get {
                return ResourceManager.GetString("MenuBackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Background Colour.
        /// </summary>
        internal static string MenuBackgroundColour {
            get {
                return ResourceManager.GetString("MenuBackgroundColour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue Theme.
        /// </summary>
        internal static string MenuBlueTheme {
            get {
                return ResourceManager.GetString("MenuBlueTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customise.
        /// </summary>
        internal static string MenuCustomise {
            get {
                return ResourceManager.GetString("MenuCustomise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Theme.
        /// </summary>
        internal static string MenuDarkTheme {
            get {
                return ResourceManager.GetString("MenuDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string MenuEnglish {
            get {
                return ResourceManager.GetString("MenuEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        internal static string MenuFont {
            get {
                return ResourceManager.GetString("MenuFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        internal static string MenuFrench {
            get {
                return ResourceManager.GetString("MenuFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        internal static string MenuGerman {
            get {
                return ResourceManager.GetString("MenuGerman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Label Colour.
        /// </summary>
        internal static string MenuLabelColour {
            get {
                return ResourceManager.GetString("MenuLabelColour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string MenuLanguage {
            get {
                return ResourceManager.GetString("MenuLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Theme.
        /// </summary>
        internal static string MenuLightTheme {
            get {
                return ResourceManager.GetString("MenuLightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night Mode.
        /// </summary>
        internal static string MenuNightMode {
            get {
                return ResourceManager.GetString("MenuNightMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change TextBox Colour.
        /// </summary>
        internal static string MenuTextBoxColour {
            get {
                return ResourceManager.GetString("MenuTextBoxColour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string MenuTheme {
            get {
                return ResourceManager.GetString("MenuTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature is below absolute zero (-273.15°C). Please enter a value of -273.15 or higher..
        /// </summary>
        internal static string MsgCelsiusRange {
            get {
                return ResourceManager.GetString("MsgCelsiusRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Error.
        /// </summary>
        internal static string MsgInputError {
            get {
                return ResourceManager.GetString("MsgInputError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid temperature. Please enter a numeric value in Celsius .
        /// </summary>
        internal static string MsgInvalidCelsius {
            get {
                return ResourceManager.GetString("MsgInvalidCelsius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input.
        /// </summary>
        internal static string MsgInvalidInput {
            get {
                return ResourceManager.GetString("MsgInvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid mass. Please enter a numeric value in kilograms.
        /// </summary>
        internal static string MsgInvalidMass {
            get {
                return ResourceManager.GetString("MsgInvalidMass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid observed wavelength. Please enter a numeric value.
        /// </summary>
        internal static string MsgInvalidObserved {
            get {
                return ResourceManager.GetString("MsgInvalidObserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parallax angle. Please enter a numeric value in arcseconds (e.g. 0.75)..
        /// </summary>
        internal static string MsgInvalidParallax {
            get {
                return ResourceManager.GetString("MsgInvalidParallax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid rest wavelength. Please enter a numeric value .
        /// </summary>
        internal static string MsgInvalidRest {
            get {
                return ResourceManager.GetString("MsgInvalidRest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mass must be greater than zero. A black hole cannot have zero or negative mass..
        /// </summary>
        internal static string MsgMassRange {
            get {
                return ResourceManager.GetString("MsgMassRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value out of range.
        /// </summary>
        internal static string MsgOutOfRange {
            get {
                return ResourceManager.GetString("MsgOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of Range.
        /// </summary>
        internal static string MsgOutOfRangeTitle {
            get {
                return ResourceManager.GetString("MsgOutOfRangeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parallax angle must be greater than zero. A zero or negative angle has no physical meaning..
        /// </summary>
        internal static string MsgParallaxRange {
            get {
                return ResourceManager.GetString("MsgParallaxRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rest wavelength cannot be zero — this would cause division by zero in the Doppler formula..
        /// </summary>
        internal static string MsgRestZero {
            get {
                return ResourceManager.GetString("MsgRestZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server error.
        /// </summary>
        internal static string MsgServerError {
            get {
                return ResourceManager.GetString("MsgServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server is not available. Make sure ServerApp is running..
        /// </summary>
        internal static string MsgServerUnavailable {
            get {
                return ResourceManager.GetString("MsgServerUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string StatusReady {
            get {
                return ResourceManager.GetString("StatusReady", resourceCulture);
            }
        }
    }
}
